name: Build Webclient
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-client:
    runs-on: ubuntu-20.04
    name: Build client
    steps:
      - name: Clone client
        uses: actions/checkout@v4

