name: Build Webclient
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-client:
    runs-on: ubuntu-latest
    name: Build client
    steps:
      - name: Clone client
        uses: actions/checkout@v4
        with:
          repository: 'swingmx/webclient'
          path: swingmusic-client

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install yarn
        run: |
          npm install -g yarn

      - name: Install dependencies & Build client
        run: |
          cd swingmusic-client
          yarn install
          yarn build --outDir ../client
          cd ..

      - name: Upload client
        uses: actions/upload-artifact@v4
        with:
          path: "client/"
          compression-level: 0

  build-wheels:
    name: Create builds on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-latest]

    steps:
      - name: Checkout swingmusic
        uses: actions/checkout@v3
        with:
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'


      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value
        #   ...

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl