name: Build Webclient
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-client:
    runs-on: ubuntu-latest
    name: Build client
    steps:
      - name: Clone client
        uses: actions/checkout@v4
        with:
          repository: 'swingmx/webclient'
          path: swingmusic-client

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install yarn
        run: |
          npm install -g yarn

      - name: Install dependencies & Build client
        run: |
          cd swingmusic-client
          yarn install
          yarn build --outDir ../client
          cd ..

      - name: Upload client
        uses: actions/upload-artifact@v4
        with:
          path: "client/"
          compression-level: 0
          name: 'client'

  build-wheels:
    name: Build wheel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout swingmusic
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build wheels
        run: pip wheel . -w wheelhouse --no-deps

      - uses: actions/upload-artifact@v4
        with:
          # name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
          compression-level: 0
          name: 'wheels'


  build-pyinstaller:
    name: Build binary on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: [build-client, build-wheels]

    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-latest ]

    steps:
      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.x"

      - name: Download artifact
        uses: actions/download-artifact@v4

      # install system packages

      - name: debug
        run:
          tree

      - name: Install swingmusic
        run: pip install *.whl

      - name: Build with Pyinstaller on ${{ matrix.os }}
        run: pyinstaller swingmusic.spec

